//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_ERROR
    {
        public string ID { get; set; }
        public string SESSION_ID { get; set; }
        public string ZIP_OR_DIR_PATH { get; set; }
        public string ISZIP { get; set; }
        public Nullable<decimal> POINTOR { get; set; }
        public string ZIP_PATH { get; set; }
        public string IGNORED { get; set; }
        public string REIMPORTED { get; set; }
        public Nullable<System.DateTime> OCURREDTIME { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string ERROR_DETAIL { get; set; }
    }
}
