//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_SESSION
    {
        public string SESSION_ID { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<decimal> LAST_TIME { get; set; }
        public string HAS_ERROR { get; set; }
        public string ZIP_OR_DIR_PATH { get; set; }
        public string COMPLETED { get; set; }
        public Nullable<decimal> FAILED_COUNT { get; set; }
        public string IS_ZIP { get; set; }
        public Nullable<decimal> ZIP_ENTRIES_COUNT { get; set; }
        public string DATA_RES_TYPE { get; set; }
        public Nullable<decimal> ZIP_ENTRY_POINTOR { get; set; }
        public string ROLLED_BACK { get; set; }
        public Nullable<decimal> ITEMS_POINT { get; set; }
        public Nullable<decimal> TOTAL_ITEM { get; set; }
        public string ZIP_ENTRY_PATH { get; set; }
        public string NOTE { get; set; }
        public string TABLENAME { get; set; }
        public string BATCH_ID { get; set; }
    }
}
