//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceExporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_AMERICA_APPLY_BRAND
    {
        public string ID { get; set; }
        public string VERSION_NO { get; set; }
        public Nullable<System.DateTime> VERSION_DATE { get; set; }
        public string ACTION_KEY { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string HEADER { get; set; }
        public Nullable<System.DateTime> HEADER_FILING_DATE { get; set; }
        public Nullable<System.DateTime> HEADER_REGISTRATION_DATE { get; set; }
        public string HEADER_STATUS_CODE { get; set; }
        public Nullable<System.DateTime> HEADER_STATUS_DATE { get; set; }
        public string HEADER_MARK_IDENTIFICATION { get; set; }
        public string HEADER_MARK_DRAWING_CODE { get; set; }
        public Nullable<System.DateTime> HEADER_ABANDONMENT_DATE { get; set; }
        public string HEADER_CANCELLATION_CODE { get; set; }
        public Nullable<System.DateTime> HEADER_CANCELLATION_DATE { get; set; }
        public string STATEMENTS { get; set; }
        public string EVENT_STATEMENTS { get; set; }
        public string PRIOR_REGISTRATION_APPLICATION { get; set; }
        public string FOREIGN_APPLICATIONS { get; set; }
        public string CLASSIFICATIONS { get; set; }
        public string INTERNATIONAL_CODE { get; set; }
        public string CORRESPONDENT { get; set; }
        public string CASE_FILE_OWNERS { get; set; }
        public string DESIGN_SEARCHES { get; set; }
        public string DESIGN_SEARCH_CODE { get; set; }
        public string INTERNATIONAL_REGISTRATION { get; set; }
        public string MADRID_INTER_FILING_REQUESTS { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string TYPE_CODE_GS { get; set; }
        public string TYPE_CODE_DM { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string BATCH { get; set; }
        public string DOC_URI { get; set; }
        public string VERSION_DATE_STR { get; set; }
        public string TRANSACTION_DATE_STR { get; set; }
        public string HEADER_FILING_DATE_STR { get; set; }
        public string HEADER_REGISTRATION_DATE_STR { get; set; }
        public string HEADER_STATUS_DATE_STR { get; set; }
        public string HEADER_ABANDONMENT_DATE_STR { get; set; }
        public string HEADER_CANCELLATION_DATE_STR { get; set; }
    }
}
