//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_AMERICA_TRIAL_BRAND
    {
        public string ID { get; set; }
        public string VERSION_NO { get; set; }
        public Nullable<System.DateTime> VERSION_DATE { get; set; }
        public string ACTION_KEY_CODE { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string JUDGMENT_NUMBER { get; set; }
        public string TYPE_CODE { get; set; }
        public Nullable<System.DateTime> FILING_DATE { get; set; }
        public Nullable<System.DateTime> STATUS_UPDATE_DATE { get; set; }
        public string STATUS_CODE { get; set; }
        public string PARTY_INFORMATION { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public string PROSECUTION_HISTORY { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
