//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_AMERICA_TRANSFER_BRAND
    {
        public string ID { get; set; }
        public string VERSION_NO { get; set; }
        public Nullable<System.DateTime> VERSION_DATE { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public string ASSIGNMENT { get; set; }
        public string ASSIGNMENT_REEL_NO { get; set; }
        public string ASSIGNMENT_FRAME_NO { get; set; }
        public Nullable<System.DateTime> ASSIGNMENT_DATE_RECORDED { get; set; }
        public string ASSIGNORS { get; set; }
        public string ASSIGNEES { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string ASSIGNMENT_CONVEYANCE_TEXT { get; set; }
        public string ASSIGNOR_PERSON_NAME { get; set; }
        public string ASSIGNEE_PERSON_NAME { get; set; }
        public string SERIAL_NO { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string BATCH { get; set; }
        public string DOC_URI { get; set; }
        public string VERSION_DATE_STR { get; set; }
        public string TRANSACTION_DATE_STR { get; set; }
        public string ASSIGNMENT_DATE_RECORDED_STR { get; set; }
    }
}
