//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_BIOLOGICAL_SEQ
    {
        public string ID { get; set; }
        public string LENGTH { get; set; }
        public string TYPE { get; set; }
        public string GN { get; set; }
        public string ORGANISM { get; set; }
        public string FEATURES { get; set; }
        public string S_FOREIGN_PATENT_SEQ_ID { get; set; }
        public string GUID { get; set; }
    }
}
