//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_MEDICINE_PATENT_HANDLE
    {
        public string ID { get; set; }
        public string T1_TI { get; set; }
        public string T1_AP { get; set; }
        public Nullable<System.DateTime> T1_AD { get; set; }
        public string T1_PN { get; set; }
        public Nullable<System.DateTime> T1_PD { get; set; }
        public string T1_PA { get; set; }
        public string T1_PAC { get; set; }
        public string T1_ADDR { get; set; }
        public string T1_INR { get; set; }
        public string T1_IC0 { get; set; }
        public string T1_IC1 { get; set; }
        public string T1_IC2 { get; set; }
        public string T1_AB { get; set; }
        public string T1_PHC { get; set; }
        public string T1_ANA { get; set; }
        public string T1_BIO { get; set; }
        public string T1_EXT { get; set; }
        public string T1_PHY { get; set; }
        public string T1_GAL { get; set; }
        public string T1_MIX { get; set; }
        public string T1_CHE { get; set; }
        public string T1_NUS { get; set; }
        public string T1_ANEF { get; set; }
        public string T1_THEF { get; set; }
        public string T1_DINT { get; set; }
        public string T1_TOXI { get; set; }
        public string T1_DIAG { get; set; }
        public string T2_AP { get; set; }
        public string T2_FORMULA { get; set; }
        public string T3_AP { get; set; }
        public string T3_CMNO { get; set; }
        public string T3_NOM1 { get; set; }
        public string T3_NOM2 { get; set; }
        public string T3_NOM3 { get; set; }
        public string T3_CN { get; set; }
        public string T3_RN { get; set; }
        public string T3_ROLES { get; set; }
        public string T3_FS { get; set; }
        public string T3_NOTE { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string FILE_PATH { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
