//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_PATENT_JUDGMENT
    {
        public string ID { get; set; }
        public string CN_COURT { get; set; }
        public string CN_DECISION_NUMBER { get; set; }
        public string ASSIGNEES { get; set; }
        public string PATENT_APPLICATION_COUNTRY { get; set; }
        public string PATENT_APPLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> PATENT_APPLICATION_DATE { get; set; }
        public string PATENT_PUBLICATION_COUNTRY { get; set; }
        public string PATENT_PUBLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> PATENT_PUBLICATION_DATE { get; set; }
        public string INVENTION_TITLE { get; set; }
        public string CLASSIFICATION_IPC { get; set; }
        public string CN_LEGAL_FILE_NUMBERS { get; set; }
        public string CN_LEGAL_PLAINTIFFS { get; set; }
        public string CN_LEGAL_DEFENDANTS { get; set; }
        public string CN_JUDGES { get; set; }
        public string CN_COURT_REPORTERS { get; set; }
        public string CN_VERDICT_DETAIL { get; set; }
        public Nullable<System.DateTime> CN_VERDICT_DATE { get; set; }
        public string PUBLICATION_COUNTRY { get; set; }
        public string PUBLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> PUBLICATION_DATE { get; set; }
        public string CN_PUB_VOL { get; set; }
        public string PATH_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
