//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_PATENT_LAWSPROCESS
    {
        public string ID { get; set; }
        public string LAW_NO { get; set; }
        public string LAW_TITLE_CN { get; set; }
        public string LAW_TITLE_EN { get; set; }
        public string LAW_DOC_NUM { get; set; }
        public string AREA_OF_LAW { get; set; }
        public string APPROVAL_DEPARTMENT { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public string ISSUING_AUTHORITY { get; set; }
        public Nullable<System.DateTime> DATE_ISSUED { get; set; }
        public Nullable<System.DateTime> IMPLEMENTATION_DATE { get; set; }
        public Nullable<System.DateTime> SIGN_DATE { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public string STATUS { get; set; }
        public string LEVEL_OF_AUTHORITY { get; set; }
        public string LAW_COUNTRY { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
