//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_PATENT_TEXTCODE
    {
        public string ID { get; set; }
        public string APPL_TYPE { get; set; }
        public string PUB_COUNTRY { get; set; }
        public string PUB_NUMBER { get; set; }
        public Nullable<System.DateTime> PUB_DATE { get; set; }
        public string PUB_KIND { get; set; }
        public string GAZETTE_REFERENCE { get; set; }
        public string APP_COUNTRY { get; set; }
        public string APP_NUMBER { get; set; }
        public Nullable<System.DateTime> APP_DATE { get; set; }
        public string CLASSIFICATION_IPCR { get; set; }
        public string INVENTION_TITLE { get; set; }
        public string ABSTRACT { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string GAZETTE_NUM { get; set; }
        public Nullable<System.DateTime> GAZETTE_DATE { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
