//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_CUSTOMS_RECORD
    {
        public string ID { get; set; }
        public string RECORD_NUM { get; set; }
        public string RECORD_TYPE { get; set; }
        public string RECORD_CLASS { get; set; }
        public string RIGHT_NAME { get; set; }
        public string RIGHT_NAME_EN { get; set; }
        public string RIGHT_NUM { get; set; }
        public string RIGHT_TYPE { get; set; }
        public string RIGHT_IMAGE { get; set; }
        public string PATH_JPG { get; set; }
        public string RIGHT_OWNER_NAME { get; set; }
        public string RIGHT_OWNER_NAME_EN { get; set; }
        public string AUTHOR_TYPE { get; set; }
        public string RIGHT_OWNER_NAME_GX { get; set; }
        public string REMARK { get; set; }
        public string RIGHT_CLASS { get; set; }
        public string TM_GS { get; set; }
        public Nullable<System.DateTime> TM_REG_DATE { get; set; }
        public Nullable<System.DateTime> TM_EXP_DATE { get; set; }
        public Nullable<System.DateTime> PT_FEE_DATE { get; set; }
        public Nullable<System.DateTime> PT_APP_DATE { get; set; }
        public Nullable<System.DateTime> PT_REG_DATE { get; set; }
        public Nullable<System.DateTime> PT_PRIORITY_DATE { get; set; }
        public string PT_GRANT { get; set; }
        public Nullable<System.DateTime> CP_COMPLETE_DATE { get; set; }
        public Nullable<System.DateTime> CP_EXP_DATE { get; set; }
        public string CP_OFFICE { get; set; }
        public string OTHER_EVIDENCE { get; set; }
        public string APPROVAL_OPINIONS { get; set; }
        public Nullable<System.DateTime> RECORD_BEGIN_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_END_DATE { get; set; }
        public string RECORD_STATE { get; set; }
        public string OWNER_INFOR_RIGHT_OWNERNAME { get; set; }
        public string OWNER_INFOR_RIGHT_OWNERNAME_EN { get; set; }
        public string OWNER_INFOR_COUNTRY { get; set; }
        public string OWNER_INFOR_AGENT_NAME { get; set; }
        public string OWNER_INFOR_TELEPHONE { get; set; }
        public string OWNER_INFOR_FAX { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
