//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_BIOLOGICAL_PROCESS
    {
        public string ID { get; set; }
        public string T1_PROJECT_NAME { get; set; }
        public string T1_APPLICANT_NAME { get; set; }
        public string T1_TITLE_OF_INVENTION { get; set; }
        public string T1_APPLICATION_FILE_REFERENCE { get; set; }
        public string T1_CURRENT_APPLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> T1_CURRENT_FILING_DATE { get; set; }
        public string T1_SEQUENCE_FILE_NAME { get; set; }
        public string T1_NUMBER_OF_SEQUENCES { get; set; }
        public string T1_SOFTWARE { get; set; }
        public string T1_PROJECT_PATH { get; set; }
        public string T1_SEQUENCE_FILE_PATH { get; set; }
        public string T1_BATCHID { get; set; }
        public string T2_CURRENT_APPLICATION_NUMBER { get; set; }
        public string T2_INFORMATION_FOR_SEQ_ID_NO { get; set; }
        public string T2_LENGTH { get; set; }
        public string T2_TYPE { get; set; }
        public string T2_ORGANISM { get; set; }
        public string T2_FEATURE { get; set; }
        public string T2_NAME_KEY { get; set; }
        public string T2_LOCATION { get; set; }
        public string T2_OTHER_INFORMATION { get; set; }
        public string T2_SEQUENCE_DESCRIPTION { get; set; }
        public string T2_BATCHID { get; set; }
        public string T3_CURRENT_APPLICATION_NUMBER { get; set; }
        public string T3_PRIOR_APPLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> T3_PRIOR_APPLICATION_DATE { get; set; }
        public string T3_BATCHID { get; set; }
        public string T4_PROJECT_NAME { get; set; }
        public string T4_APPLICANT_NAME { get; set; }
        public string T4_TITLE_OF_INVENTION { get; set; }
        public string T4_APPLICATION_FILE_REFERENCE { get; set; }
        public string T4_CURRENT_APPLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> T4_CURRENT_FILING_DATE { get; set; }
        public string T4_SEQUENCE_FILE_NAME { get; set; }
        public string T4_NUMBER_OF_SEQUENCES { get; set; }
        public string T4_SOFTWARE { get; set; }
        public string T4_PROJECT_PATH { get; set; }
        public string T4_SEQUENCE_FILE_PATH { get; set; }
        public string T4_BATCHID { get; set; }
        public string T5_CURRENT_APPLICATION_NUMBER { get; set; }
        public string T5_INFORMATION_FOR_SEQ_ID_NO { get; set; }
        public string T5_LENGTH { get; set; }
        public string T5_TYPE { get; set; }
        public string T5_ORGANISM { get; set; }
        public string T5_FEATURE { get; set; }
        public string T5_NAME_KEY { get; set; }
        public string T5_LOCATION { get; set; }
        public string T5_OTHER_INFORMATION { get; set; }
        public string T5_SEQUENCE_DESCRIPTION { get; set; }
        public string T5_BATCHID { get; set; }
        public string T6_CURRENT_APPLICATION_NUMBER { get; set; }
        public string T6_PRIOR_APPLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> T6_PRIOR_APPLICATION_DATE { get; set; }
        public string T6_BATCHID { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
