//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_LICENSE_PROCESSINFO
    {
        public string ID { get; set; }
        public string CN_BRAND_LICENSE_ID { get; set; }
        public string MARK_CN_ID { get; set; }
        public string SEQUENCE { get; set; }
        public string XKBAGGQH { get; set; }
        public string PAGENUM { get; set; }
        public string GGTYPE { get; set; }
        public string BAH { get; set; }
        public string XKQX { get; set; }
        public string XKR { get; set; }
        public string XKR_NAME { get; set; }
        public string BXKR { get; set; }
        public string BXKR_NAME { get; set; }
        public string XKGS { get; set; }
        public string XKBAGGRQ { get; set; }
    }
}
