//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_CIRCUITLAYOUT
    {
        public string ID { get; set; }
        public string BTDJH { get; set; }
        public Nullable<System.DateTime> BTSQR { get; set; }
        public Nullable<System.DateTime> GGR { get; set; }
        public string GGH { get; set; }
        public string BTMC { get; set; }
        public string LB { get; set; }
        public string BTCZR { get; set; }
        public Nullable<System.DateTime> BTWCR { get; set; }
        public Nullable<System.DateTime> BTLYR { get; set; }
        public string BTQLRS { get; set; }
        public string DLJG { get; set; }
        public string DLR { get; set; }
        public Nullable<System.DateTime> BTQMR { get; set; }
        public string PATH { get; set; }
        public string SHWINFO { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
