//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_BRAND_LICENSE
    {
        public string ID { get; set; }
        public string MARK_CN_ID { get; set; }
        public string NAMEINFO_NAME { get; set; }
        public string BASEINFO_REGISTRATION_NO { get; set; }
        public string LICENSEPROCESSINFO_SEQUENCE { get; set; }
        public string LICENSEPROCESSINFO_XKBAGGQH { get; set; }
        public string LICENSEPROCESSINFO_PAGENUM { get; set; }
        public string LICENSEPROCESSINFO_GGTYPE { get; set; }
        public string LICENSEPROCESSINFO_BAH { get; set; }
        public string LICENSEPROCESSINFO_XKQX { get; set; }
        public string LICENSEPROCESSINFO_XKR { get; set; }
        public string LICENSEPROCESSINFO_XKR_NAME { get; set; }
        public string LICENSEPROCESSINFO_BXKR { get; set; }
        public string LICENSEPROCESSINFO_BXKR_NAME { get; set; }
        public string LICENSEPROCESSINFO_XKGS { get; set; }
        public Nullable<System.DateTime> LICENSEPROCESSINFO_XKBAGGRQ { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
