//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_MEDICINE_PATENT_TRANS
    {
        public string ID { get; set; }
        public string T1_ETI { get; set; }
        public string T1_AP { get; set; }
        public Nullable<System.DateTime> T1_AD { get; set; }
        public string T1_PN { get; set; }
        public Nullable<System.DateTime> T1_PD { get; set; }
        public string T1_EPA { get; set; }
        public string T1_EPAC { get; set; }
        public string T1_EADDR { get; set; }
        public string T1_EINR { get; set; }
        public string T1_IC0 { get; set; }
        public string T1_IC1 { get; set; }
        public string T1_IC2 { get; set; }
        public string T1_EAB { get; set; }
        public string T1_PHC { get; set; }
        public string T1_EANA { get; set; }
        public string T1_EBIO { get; set; }
        public string T1_EEXT { get; set; }
        public string T1_EPHY { get; set; }
        public string T1_EGAL { get; set; }
        public string T1_EMIX { get; set; }
        public string T1_ECHE { get; set; }
        public string T1_ENUS { get; set; }
        public string T1_EANEF { get; set; }
        public string T1_ETHEF { get; set; }
        public string T1_EDINT { get; set; }
        public string T1_ETOXI { get; set; }
        public string T1_EDIAG { get; set; }
        public string T2_AP { get; set; }
        public string T2_EFORMULA { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string FILE_PATH { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
