//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_BRAND
    {
        public string ID { get; set; }
        public string MARK_CN_ID { get; set; }
        public string NAMEINFO_NAME { get; set; }
        public string BASEINFO_ORIGINAL_LANGUAGE { get; set; }
        public string BASEINFO_REGISTRATION_NO { get; set; }
        public string BASEINFO_APPLICATION_NO { get; set; }
        public Nullable<decimal> BASEINFO_ICN { get; set; }
        public string BASEINFO_TRADEMARK_TYPE { get; set; }
        public string BASEINFO_CURRENT_STATE_RIGHT { get; set; }
        public string BASEINFO_SPECIFIED_COLOR { get; set; }
        public Nullable<System.DateTime> DATEINFO_APPLICATION_DATE { get; set; }
        public Nullable<System.DateTime> DATEINFO_REG_DATE { get; set; }
        public Nullable<System.DateTime> SPECIAL_RIGHT_STARTDATE { get; set; }
        public Nullable<System.DateTime> SPECIAL_RIGHT_ENDDATE { get; set; }
        public Nullable<System.DateTime> DATEINFO_PRIORITY_RIGHT_DATE { get; set; }
        public string APPLICATION_PERSION_INFOS { get; set; }
        public string SERVICE_LIST { get; set; }
        public string OTHERINFO { get; set; }
        public string PATH_JPG { get; set; }
        public string PATH_JPG_SF { get; set; }
        public string PATH_FILE { get; set; }
        public string EXIST_JPG { get; set; }
        public string EXIST_JPG_SF { get; set; }
        public string EXIST_FILE { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string TRADEMARK_NOTICE_STATUS { get; set; }
    }
}
