//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_BRAND_TRANS_INFO
    {
        public string ID { get; set; }
        public string TRANSFER_ID { get; set; }
        public string MARK_CN_ID { get; set; }
        public string SEQUENCE { get; set; }
        public string ZHRGGQH { get; set; }
        public string YM { get; set; }
        public string ZHGGRQ { get; set; }
        public string ZHRR { get; set; }
        public string ZHRR_NAME { get; set; }
        public string SHRR { get; set; }
        public string SHRR_NAME { get; set; }
    }
}
