//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_PATENT_INVALID
    {
        public string ID { get; set; }
        public string CN_DECISION_NUMBER { get; set; }
        public Nullable<System.DateTime> CN_DECISION_DATE { get; set; }
        public string APPLICATION_COUNTRY { get; set; }
        public string APPLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE { get; set; }
        public string ASSIGNEES { get; set; }
        public string PUBLICATION_COUNTRY { get; set; }
        public string PUBLICATION_NUMBER { get; set; }
        public Nullable<System.DateTime> PUBLICATION_DATE { get; set; }
        public string INVENTION_TITLE { get; set; }
        public string CLASSIFICATION_LOCARNO { get; set; }
        public string CN_APPELLANT { get; set; }
        public string CN_EXAMINERS { get; set; }
        public string PUBLICATION_INFO_COUNTRY { get; set; }
        public string PUBLICATION_INFO_NUMBER { get; set; }
        public Nullable<System.DateTime> PUBLICATION_INFO_DATE { get; set; }
        public string CN_PUB_VOL { get; set; }
        public string CN_LAW_REFERENCE { get; set; }
        public string CN_MAIN_POINT { get; set; }
        public string ABSTRACT { get; set; }
        public string KEYWORD { get; set; }
        public string CN_BRIEF_HISTORY { get; set; }
        public string CN_REASONING { get; set; }
        public string CN_HOLDING { get; set; }
        public string PATH_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
