//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_COURTCASE_PROCESS
    {
        public string ID { get; set; }
        public string PN { get; set; }
        public string C_LEGAL_NUM { get; set; }
        public string C_YEAR { get; set; }
        public string C_VERDICTTYPE { get; set; }
        public string C_TITLE { get; set; }
        public string C_NAME { get; set; }
        public string C_ORIGIN_PASS { get; set; }
        public string C_IP_TYPES { get; set; }
        public string C_COURT_NAME { get; set; }
        public string C_COURT_PROVINCE { get; set; }
        public string C_COURT_CITY { get; set; }
        public string C_COURT_CODE { get; set; }
        public string C_COURT_LEVEL { get; set; }
        public string C_COURT_NUM { get; set; }
        public string C_CASETYPE { get; set; }
        public string C_SUBBRANCH { get; set; }
        public string C_VERDICTRESULT { get; set; }
        public string C_APPELLENTINFOS { get; set; }
        public string C_PLAINTIFF_PRES { get; set; }
        public string C_PLAINTIFF_AGENT_NAMES { get; set; }
        public string C_PLAINTIFF_AGENT_ORGS { get; set; }
        public string C_APPELLEEINFOS { get; set; }
        public string C_DEFENDENT_PRES { get; set; }
        public string C_DEFENDENT_AGENT_NAMES { get; set; }
        public string C_DEFENDENT_AGENT_ORGS { get; set; }
        public string C_THIRD_PERSONINFOS { get; set; }
        public string C_THIRD_PERSON_PRES { get; set; }
        public string C_THIRD_PERSON_AGENT_NAMES { get; set; }
        public string C_THIRD_PERSON_AGENT_ORGS { get; set; }
        public string C_LEGALNUMBER_SUPERIORS { get; set; }
        public Nullable<System.DateTime> C_STARTDATE { get; set; }
        public string C_APPLYCOST { get; set; }
        public string C_JUDGECOST { get; set; }
        public string C_VD_IVFO { get; set; }
        public string C_PRE_JUDGE { get; set; }
        public string C_PROXY_PRE_JUDGE { get; set; }
        public string C_JUDGE { get; set; }
        public string C_PROXY_JUDGE { get; set; }
        public string C_JURY { get; set; }
        public string C_CLERK { get; set; }
        public Nullable<System.DateTime> C_VERDICTDATE { get; set; }
        public string S_YEAR { get; set; }
        public string HOLDINGTYPE { get; set; }
        public string LAWREFERENCES { get; set; }
        public string EVIDENCES { get; set; }
        public string C_PL_N_KEY { get; set; }
        public string C_PL_N_KEY_STANDARD { get; set; }
        public string ALLTEXT { get; set; }
        public string CASEFAMILY { get; set; }
        public string PATH_PDF { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_PDF { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string C_ID { get; set; }
        public string C_PT_NS { get; set; }
        public string C_PL_NS { get; set; }
        public string C_TR_NS { get; set; }
    }
}
