//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_BRAND_CLASSIFICATION
    {
        public string ID { get; set; }
        public string CLNO { get; set; }
        public string F_CLNO { get; set; }
        public string GOODS_SERVICE_CN { get; set; }
        public string GOODS_SERVICE_EN { get; set; }
        public string ZHUSHI_CN { get; set; }
        public string ZHUSHI_EN { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string FILE_PATH { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
