//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_WELLKNOWN_BRAND
    {
        public string ID { get; set; }
        public string MARK_CN_ID { get; set; }
        public string NAMEINFO_NAME { get; set; }
        public string BASEINFO_REGISTRATION_NO { get; set; }
        public string TRADEMARK_CERTIFICATION { get; set; }
        public string TRADEMARK_AREA { get; set; }
        public string TRADEMARK_DETERMINATION_ORGAN { get; set; }
        public string TRADEMARK_DETERMINATION_METHOD { get; set; }
        public string TRADEMARK_DETERMINATION_BATCH { get; set; }
        public string TRADEMARK_DETERMINATION_TIME { get; set; }
        public string TRADEMARK_WEBSITE { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string SEQUENCE { get; set; }
    }
}
