//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_BRAND_TRANSFER
    {
        public string ID { get; set; }
        public string MARK_CN_ID { get; set; }
        public string NAMEINFO_NAME { get; set; }
        public string BASEINFO_REGISTRATION_NO { get; set; }
        public string TRANSFERINFO_SEQUENCE { get; set; }
        public string TRANSFERINFO_ZHRGGQH { get; set; }
        public string TRANSFERINFO_YM { get; set; }
        public string TRANSFERINFO_ZHRR { get; set; }
        public string TRANSFERINFO_ZHRR_NAME { get; set; }
        public string TRANSFERINFO_SHRR { get; set; }
        public string TRANSFERINFO_SHRR_NAME { get; set; }
        public Nullable<System.DateTime> TRANSFERINFO_ZHGGRQ { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
