//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_CHINA_PATENT_STANDARDFULLTXT
    {
        public string ID { get; set; }
        public string STA_PUB_COUNTRY { get; set; }
        public string STA_PUB_NUMBER { get; set; }
        public string STA_PUB_KIND { get; set; }
        public Nullable<System.DateTime> STA_PUB_DATE { get; set; }
        public string ORI_PUB_COUNTRY { get; set; }
        public string ORI_PUB_NUMBER { get; set; }
        public string ORI_PUB_KIND { get; set; }
        public Nullable<System.DateTime> ORI_PUB_DATE { get; set; }
        public string STA_APP_COUNTRY { get; set; }
        public string STA_APP_NUMBER { get; set; }
        public Nullable<System.DateTime> STA_APP_DATE { get; set; }
        public string ORI_APP_COUNTRY { get; set; }
        public string ORI_APP_NUMBER { get; set; }
        public Nullable<System.DateTime> ORI_APP_DATE { get; set; }
        public string DESIGN_PATENTNUMBER { get; set; }
        public string CLASSIFICATIONIPCR { get; set; }
        public string CLASSIFICATIONLOCARNO { get; set; }
        public string INVENTIONTITLE { get; set; }
        public string FULLDOCIMAGE_NUMBEROFFIGURES { get; set; }
        public string FULLDOCIMAGE_TYPE { get; set; }
        public string PATH_STA_FULLTEXT { get; set; }
        public string EXIST_STA_FULLTEXT { get; set; }
        public string PATH_DI_ABS_BIB { get; set; }
        public string PATH_DI_CLA_DES_DRA { get; set; }
        public string PATH_DI_BRI_DBI { get; set; }
        public string EXIST_DI_ABS_BIB { get; set; }
        public string EXIST_DI_CLA_DES_DRA { get; set; }
        public string EXIST_DI_BRI_DBI { get; set; }
        public string PATH_FULLTEXT { get; set; }
        public string EXIST_FULLTEXT { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string ABSTRACT { get; set; }
        public string DESIGNBRIEFEXPLANATION { get; set; }
        public string VER_CLASSIFICATIONLOCARNO { get; set; }
        public string STA_CLASSIFICATIONLOCARNO { get; set; }
        public string ORI_CLASSIFICATIONLOCARNO { get; set; }
        public string OTH_CLASSIFICATIONLOCARNO { get; set; }
    }
}
