//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_COMMUNITY_INTELLECTUALRECORD
    {
        public string ID { get; set; }
        public string B_NO { get; set; }
        public string B_ID { get; set; }
        public string B_NAME { get; set; }
        public string B_NAME_EN { get; set; }
        public string B_ISBN { get; set; }
        public string B_SNAME { get; set; }
        public string S_SNAME_EN { get; set; }
        public string B_AUTHOR { get; set; }
        public string B_REEDITOR { get; set; }
        public Nullable<System.DateTime> B_DATE { get; set; }
        public string B_PUBHOUSE { get; set; }
        public string B_CLC { get; set; }
        public string B_REVISION { get; set; }
        public string B_LANGUAGE { get; set; }
        public string B_KEYWORD { get; set; }
        public string B_SUMMARY { get; set; }
        public string B_CIP { get; set; }
        public string B_PRICE { get; set; }
        public string B_PRINT_NAME { get; set; }
        public string B_PAGES { get; set; }
        public string B_TEXT_FLAG { get; set; }
        public string B_COVER_FLAG { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
