//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_COMPANY_CODE_LIBRARY
    {
        public string ID { get; set; }
        public string SID { get; set; }
        public string P_RID { get; set; }
        public string GSMC_STD { get; set; }
        public string NID { get; set; }
        public string GSMC_ORI { get; set; }
        public string LANG { get; set; }
        public string ORIGIN { get; set; }
        public string TYPE { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
