//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceExporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_DATA_RESOURCE_TYPES_DETAIL
    {
        public decimal ID { get; set; }
        public string CHINESE_NAME { get; set; }
        public string TABLE_NAME { get; set; }
        public string IMPLEMENTED_IMPORT_LOGIC { get; set; }
        public string IN_PROCESS { get; set; }
        public string HASCHECKER { get; set; }
        public string HASEXPORTER { get; set; }
        public string IS_PAT { get; set; }
        public string INDEX_TYPE { get; set; }
        public string F_DATA_NUM { get; set; }
    }
}
