//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_DOCDB
    {
        public string ID { get; set; }
        public string STA_PUB_COUNTRY { get; set; }
        public string STA_PUB_NUMBER { get; set; }
        public string STA_PUB_KIND { get; set; }
        public Nullable<System.DateTime> STA_PUB_DATE { get; set; }
        public string DOCDB_PUB_COUNTRY { get; set; }
        public string DOCDB_PUB_NUMBER { get; set; }
        public string DOCDB_PUB_KIND { get; set; }
        public Nullable<System.DateTime> DOCDB_PUB_DATE { get; set; }
        public string EPODC_PUB_NUMBER { get; set; }
        public string ORI_PUB_COUNTRY { get; set; }
        public string ORI_PUB_NUMBER { get; set; }
        public string ORI_PUB_KIND { get; set; }
        public Nullable<System.DateTime> ORI_PUB_DATE { get; set; }
        public string STA_APP_COUNTRY { get; set; }
        public string STA_APP_NUMBER { get; set; }
        public string STA_APP_KIND { get; set; }
        public Nullable<System.DateTime> STA_APP_DATE { get; set; }
        public string DOCDB_APP_COUNTRY { get; set; }
        public string DOCDB_APP_NUMBER { get; set; }
        public string DOCDB_APP_KIND { get; set; }
        public Nullable<System.DateTime> DOCDB_APP_DATE { get; set; }
        public string EPODC_APP_NUMBER { get; set; }
        public string ORI_APP_NUMBER { get; set; }
        public string ORI_APP_COUNTRY { get; set; }
        public string ORI_APP_KIND { get; set; }
        public Nullable<System.DateTime> ORI_APP_DATE { get; set; }
        public string CLASSIFICATIONIPCRDETAILS { get; set; }
        public string INVENTIONTITLE_EN { get; set; }
        public string INVENTIONTITLE_ZH { get; set; }
        public string ABSTRACT_EN { get; set; }
        public string ABSTRACT_ZH { get; set; }
        public string PATH_XML { get; set; }
        public string EXIST_XML { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
