//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_FOREIGN_PATENT_SEQUENCE
    {
        public string ID { get; set; }
        public string FILENAME { get; set; }
        public Nullable<System.DateTime> DATEEXCHANGE { get; set; }
        public Nullable<System.DateTime> DATEPRODUCED { get; set; }
        public string PATCNT { get; set; }
        public string FILECNT { get; set; }
        public string DATASIZE { get; set; }
        public string MD5 { get; set; }
        public string STATUS { get; set; }
        public string DOCLIST_TOPIC { get; set; }
        public string DOCLIST_COUNTRY { get; set; }
        public string DOCLIST_DOCNUMBER { get; set; }
        public string DOCLIST_KIND { get; set; }
        public string DOCLIST_PNO { get; set; }
        public string DOCLIST_PNS { get; set; }
        public Nullable<System.DateTime> DOCLIST_DATEPUBLICATION { get; set; }
        public string DOCLIST_FORMAT { get; set; }
        public string DOCLIST_PATH { get; set; }
        public string DOCLIST_STATUS { get; set; }
        public string DOCLIST_FILENAME { get; set; }
        public string DOCLIST_FILETYPE { get; set; }
        public string DOCLIST_SECTION { get; set; }
        public Nullable<int> DOCLIST_SEQLIST_AMOUNT { get; set; }
        public string DOCLIST_SEQLIST_SEQ_ID { get; set; }
        public string DOCLIST_SEQLIST_SEQ_LENGTH { get; set; }
        public string DOCLIST_SEQLIST_SEQ_TYPE { get; set; }
        public string DOCLIST_SEQLIST_SEQ_GN { get; set; }
        public string DOCLIST_SEQLIST_SEQ_OG { get; set; }
        public string DOCLIST_SEQLIST_SEQ_ORGANISM { get; set; }
        public string DOCLIST_SEQLIST_SEQ_FEATURES { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
