//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_IMPORT_BATH
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public string ISCOMPLETED { get; set; }
        public Nullable<decimal> FILECOUNT { get; set; }
        public string IS_DIR_MODE { get; set; }
        public string DIR_PATH { get; set; }
        public string RES_TYPE { get; set; }
        public Nullable<decimal> LAST_TIME { get; set; }
        public Nullable<decimal> HANDLED_ITEM_COUNT { get; set; }
        public string NOTE { get; set; }
    }
}
