//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_JOURNAL_PROJECT_ABSTRACT
    {
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string ID { get; set; }
        public string SYSTEM_FIELD_RID { get; set; }
        public string CLASS_INFO_CLASS_CODE { get; set; }
        public string CLASS_INFO_SUBJECT_ALL { get; set; }
        public string CLASS_INFO_ASJC { get; set; }
        public string CLASS_INFO_CJCR { get; set; }
        public string CLASS_INFO_CSSCI { get; set; }
        public string CLASS_INFO_JCR { get; set; }
        public string CLASS_INFO_PKU { get; set; }
        public string CLASS_INFO_SFX { get; set; }
        public string CLASS_INFO_INDEXBY { get; set; }
        public string ARTICLE_INFO_TITLE_SOURCE { get; set; }
        public string ARTICLE_INFO_TITLE_CN { get; set; }
        public string ARTICLE_INFO_TITLE_EN { get; set; }
        public string ARTICLE_INFO_VENDOR { get; set; }
        public string ARTICLE_INFO_COUNTRY { get; set; }
        public string ARTICLE_INFO_LANGUAGE { get; set; }
        public string ARTICLE_INFO_KEYWORDS_ALL { get; set; }
        public string ARTICLE_INFO_KEYWORDS_SOURCE { get; set; }
        public string ARTICLE_INFO_KEYWORDS_CN { get; set; }
        public string ARTICLE_INFO_KEYWORDS_EN { get; set; }
        public string ARTICLE_INFO_FUND { get; set; }
        public string ARTICLE_INFO_SYS_SCORE { get; set; }
        public string ARTICLE_INFO_PAGE_COUNT { get; set; }
        public string ARTICLE_INFO_PAGES { get; set; }
        public string RESOURCE_INFO { get; set; }
        public string FIRST_AUTHOR_SOURCE { get; set; }
        public string FIRST_AUTHOR_CN { get; set; }
        public string FIRST_AUTHOR_EN { get; set; }
        public string JOURNAL_INFO_JID { get; set; }
        public string JOURNAL_INFO_LITERATURE_ALL { get; set; }
        public string JOURNAL_INFO_LITERATURE_SOURCE { get; set; }
        public string JOURNAL_INFO_LITERATURE_CN { get; set; }
        public string JOURNAL_INFO_LITERATURE_EN { get; set; }
        public string JOURNAL_INFO_DOI { get; set; }
        public string JOURNAL_INFO_ISSN { get; set; }
        public string JOURNAL_INFO_CN { get; set; }
        public string JOURNAL_INFO_EISSN { get; set; }
        public string JOURNAL_INFO_VOLUME { get; set; }
        public string JOURNAL_INFO_ISSUE { get; set; }
        public string JOURNAL_INFO_MONTH { get; set; }
        public string JOURNAL_INFO_YEAR { get; set; }
        public string JOURNAL_INFO_PUB_DATE { get; set; }
        public string DOCUMENT_TYPE_SCHOLARLY { get; set; }
        public string DOCUMENT_TYPE_CORE_JOURNAL { get; set; }
        public string DOCUMENT_TYPE_OPEN_ACCESS { get; set; }
        public string DOCUMENT_TYPE_PEER_REVIEW { get; set; }
        public string DOCUMENT_TYPE_FREE_CONTENT { get; set; }
        public string DOCUMENT_TYPE_FUND_SUPPORT { get; set; }
        public string DOCUMENT_TYPE_DOC_TYPE { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public string ARTICLE_INFO_ABSTRACT_ALL { get; set; }
        public string ARTICLE_INFO_ABSTRACT_SOURCE { get; set; }
        public string ARTICLE_INFO_ABSTRACT_CN { get; set; }
        public string ARTICLE_INFO_ABSTRACT_EN { get; set; }
        public string ORG_SOURCE { get; set; }
        public string ORG_CN { get; set; }
        public string ORG_EN { get; set; }
        public string AUTHOR_SOURCE { get; set; }
        public string AUTHOR_CN { get; set; }
        public string AUTHOR_EN { get; set; }
    }
}
