//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceExporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_MADRID_BRAND_PURCHASE
    {
        public string ID { get; set; }
        public string INTREGN { get; set; }
        public string OOCD { get; set; }
        public Nullable<System.DateTime> INTREGD { get; set; }
        public Nullable<System.DateTime> EXPDATE { get; set; }
        public string ORIGLAN { get; set; }
        public string HOLGR { get; set; }
        public string HOLGR_NAME_NAMEL { get; set; }
        public string REPGR { get; set; }
        public string PHOLGR { get; set; }
        public string IMAGE_COLOUR { get; set; }
        public string IMAGE_TEXT { get; set; }
        public string VIENNAGR_VIECLAI { get; set; }
        public string VIENNAGR_VIECLA3 { get; set; }
        public string THRDMAR { get; set; }
        public string SOUMARI { get; set; }
        public string COLMARI { get; set; }
        public string PREREGG { get; set; }
        public string COLCLAGR { get; set; }
        public string MARDESGR { get; set; }
        public string MARTRGR { get; set; }
        public string DISCLAIMGR { get; set; }
        public string BASICGS { get; set; }
        public string BASREGGR { get; set; }
        public string BASAPPGR { get; set; }
        public string PRIGR { get; set; }
        public string SENGRP { get; set; }
        public string DESAG_DCPCD { get; set; }
        public string DESPG_DCPCD { get; set; }
        public string DESPG2_DCPCD { get; set; }
        public string PATH_XML { get; set; }
        public string PATH_PIC { get; set; }
        public string PATH_PIC_SF { get; set; }
        public string EXIST_XML { get; set; }
        public string EXIST_PIC { get; set; }
        public string EXIST_PIC_SF { get; set; }
        public string TYPMARI { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string BASICGS_GSGR_NICCLAI { get; set; }
        public string DOC_FILE_NAME { get; set; }
        public string BATCH { get; set; }
        public string DOC_URI { get; set; }
        public string INTREGD_STR { get; set; }
        public string EXPDATE_STR { get; set; }
    }
}
