//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_PATENT_PAYMENT
    {
        public string ID { get; set; }
        public string FEE { get; set; }
        public string FEETYPE { get; set; }
        public string RECEIPTION { get; set; }
        public string REGISTERCODE { get; set; }
        public string APPLYNUM { get; set; }
        public string HKINFO { get; set; }
        public string STATE { get; set; }
        public Nullable<System.DateTime> HKDATE { get; set; }
        public Nullable<System.DateTime> RECEIPTIONDATE { get; set; }
        public string PAYMENTUNITTYPE { get; set; }
        public string EN_FEETYPE { get; set; }
        public string EN_STATE { get; set; }
        public string APPLYNUM_NEW { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string FILE_PATH { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
    }
}
