//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_T_BIOLOGICAL_PRIORITY_FY
    {
        public string ID { get; set; }
        public string CURRENT_APPLICATION_NUMBER { get; set; }
        public string PRIOR_APPLICATION_NUMBER { get; set; }
        public string PRIOR_APPLICATION_FILING_DATE { get; set; }
        public string BATCHID { get; set; }
        public string BIO_ID { get; set; }
    }
}
