//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_T_BIOLOGICAL_FY
    {
        public string PROJECT_NAME { get; set; }
        public string APPLICANT_NAME { get; set; }
        public string TITLE_OF_INVENTION { get; set; }
        public string APPLICATION_FILE_REFERENCE { get; set; }
        public string CURRENT_APPLICATION_NUMBER { get; set; }
        public string CURRENT_FILING_DATE { get; set; }
        public string SEQUENCE_FILE_NAME { get; set; }
        public string NUMBER_OF_SEQUENCES { get; set; }
        public string SOFTWARE { get; set; }
        public string PROJECT_PATH { get; set; }
        public string SEQUENCE_FILE_PATH { get; set; }
        public string BATCHID { get; set; }
        public string IMPORT_SESSION_ID { get; set; }
        public Nullable<System.DateTime> IMPORT_TIME { get; set; }
        public string ARCHIVE_INNER_PATH { get; set; }
        public string FILE_PATH { get; set; }
        public Nullable<decimal> SESSION_INDEX { get; set; }
        public string ID { get; set; }
    }
}
