//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheDataResourceImporter
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_SJZYZTSXXX
    {
        public decimal ID { get; set; }
        public string F_DATANUM { get; set; }
        public string F_DATANAME { get; set; }
        public string F_DATACLASS { get; set; }
        public string F_DATABIGCLASS { get; set; }
        public string F_DATALITCLASS { get; set; }
        public string F_DATANEEDNO { get; set; }
        public string F_DATACOUNTRY { get; set; }
        public Nullable<System.DateTime> F_STARTTIME { get; set; }
        public Nullable<System.DateTime> F_ENDTIME { get; set; }
        public string F_TIMEREMARK { get; set; }
        public string F_DATALANG { get; set; }
        public Nullable<int> F_DATATOTALNUM { get; set; }
        public string F_UPDATECYCLE { get; set; }
        public string F_DATAFORMAT { get; set; }
        public string F_PACKAGEFORMAT { get; set; }
        public string F_DATATYPE { get; set; }
        public string F_ISAPPLIED { get; set; }
        public string F_ISSOLD { get; set; }
        public string F_DATASOURCE { get; set; }
        public string F_DATAORG { get; set; }
        public string F_ISSTRUCTURED { get; set; }
        public string F_COLLECTIONMETHODS { get; set; }
        public string F_KEEPINGORG { get; set; }
        public string F_KEEPINGORGID { get; set; }
        public Nullable<System.DateTime> F_KEEPTIME { get; set; }
        public string F_ISHOTSPOT { get; set; }
        public string F_MANAGELEVEL { get; set; }
        public string F_APPLYSYSTEM { get; set; }
        public string F_USEDESCRIBE { get; set; }
        public string F_DATAMISS { get; set; }
        public string F_DATAREMARK { get; set; }
        public string F_DESCDOCUMENT { get; set; }
        public string F_ONEMEDIUM { get; set; }
        public string F_ONEADDRESS { get; set; }
        public string F_ONEDATAADD { get; set; }
        public Nullable<decimal> F_ONECAPACITY { get; set; }
        public string F_TWOMEDIUM { get; set; }
        public string F_TWOADDRESS { get; set; }
        public string F_TWODATAADD { get; set; }
        public string F_RECOVERYMEDIUM { get; set; }
        public string F_RECOVERYADDRESS { get; set; }
        public string F_RECOVERYDATAADD { get; set; }
        public Nullable<decimal> F_RECOVERYCAPACITY { get; set; }
        public string F_STATUS { get; set; }
        public string F_ISRECOVERY { get; set; }
        public Nullable<decimal> F_TWOCAPACITY { get; set; }
        public string F_CATALOGUER { get; set; }
        public string F_CATALOGUERID { get; set; }
        public string F_STSJNAME { get; set; }
        public string F_DATASAMPLE { get; set; }
    }
}
